### PR TITLE
Migrate to async-rest

### PR DESCRIPTION
**Pull request by picatz**
This PR uses [`async-rest`](https://github.com/socketry/async-rest) to manage GET/POST requests for the majority of the library.

The streaming API requests are still managed with `async-http`.

### CODE REVIEW

**Comment by picatz** [comment]
🙈 Going to wait for a response from @ioquatix on https://github.com/socketry/async-rest/issues/1 before finalizing this PR.

**Comment by picatz** [comment]
@ioquatix If I'm not mistaken, I think with 424eb01, which has the basic custom-ish representation, I should be good to go. Specs pass and everything seems to work as intended 👍 

I was confused with how to properly put it together, but I think I got it now.

**Comment by ioquatix** [comment]
The way you are using it is not leveraging the structure/model of REST as efficiently as you could be - and you are also not caching the HTTP connection due to that design, so I'm happy to make a few manipulations to show you how it should fit together.

**Comment by picatz** [comment]
Not exactly sure if I'll ever migrate over to `async-rest`, but this might be something I revisit in the future. For now, I'm going to close this to prevent confusion about my intentions.

Thank you ioquatix for you guidance and help on this. 🙇

**Pull request closed without merging**
